`ifndef SYSTOLIC_PARAMETERS_SVH
`define SYSTOLIC_PARAMETERS_SVH

`define DATA_WIDTH 8
`define ACCUMULATOR_WIDTH 26
`define ARRAY_ROWS 5
`define ARRAY_COLUMNS 5
`define INPUT_FEATURE_COUNT 784
`define LAYER_1_NEURON_COUNT 30
`define LAYER_2_NEURON_COUNT 20
`define LAYER_3_NEURON_COUNT 10
`define GLOBAL_BUFFER_DEPTH 30

`endif
